image: maven:3.3.9


stages:
  - build
  - test
build:
  stage: build
  script: mvn clean package
  artifacts:
    paths: 
    - https://rishijfrog.jfrog.io/rishijfrog/libs-release-local
unitTests:
  stage: test
  script:
    - mvn test