image: maven:3.3.9

before_script:

  - curl -fL https://getcli.jfrog.io | sh

  - ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password=$ARTIFACTORY_PASS --interactive=false
stages:
  - build
  - test
build:
    stage: build
    script: 
    
    -   mvn clean package
  
    - ./jfrog rt u "target/*.jar" testrepo 
unitTests:
  stage: test
  script:
    - mvn test

   