image: maven:3.3.9

stages:
  - build
  - test
build:
  stage: build
  script: mvn clean package
  artifacts:
    paths:
      - spring-blogs/target/myApp-*.jar
unitTests:
  stage: test
  script:
    - mvn test