image: maven:3.3.9

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/


stages:
  - build
  - test
build:
  stage: build
  script: mvn clean package
unitTests:
  stage: test
  script:
    - mvn test