stages:
  - build
  - test
  - Build-Push Docker image
  
build:
  image: maven:3-jdk-8
  stage: build
  before_script:
  # Install JFrog CLI
  - curl -fL https://getcli.jfrog.io | sh
  # Configure Artifactory instance with JFrog CLI
  - ./jfrog rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASS
  - ./jfrog rt c show
  # Set the M2_HOME environment variable
  - export M2_HOME=/usr/share/maven
  # Replace the repository name in the configuration.yml to the correct one.
  - sed -i 's,MAVEN_REPO_KEY,'"$MAVEN_REPO_KEY"',g' configuration.yml
  
  script:
    # Run the MVN command
    - ./jfrog rt mvn "clean install -DskipTests" configuration.yml --build-name=gitlabci-maven-artifactory --build-number=$CI_JOB_ID
    # Collect the environment variables
    - ./jfrog rt bce gitlabci-maven-artifactory $CI_JOB_ID
    # Pass the build information to Artifactory
    - ./jfrog rt bp gitlabci-maven-artifactory $CI_JOB_ID
    
unitTests:
  image: maven:3-jdk-8
  stage: test
  script:
    - mvn test

Docker image: 
  image: docker:latest
  

  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    LATEST_VER: angristan/app:latest
    MAJOR_VER: angristan/app:2
    MINOR_VER: angristan/app:2.3
    PATCH_VER: angristan/app:2.3.1
  services:
  - docker:dind
  stage: Build-Push Docker image
  script:
  - docker info
  - docker build -t rishabh050189/spring-blogs:"$CI_JOB_ID" .
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  - docker push rishabh050189/spring-blogs:"$CI_JOB_ID" 

  only:
    - docker
