image: maven:3.3.9

before_script:

  - curl -fL https://getcli.jfrog.io | sh

  - ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password=$ARTIFACTORY_PASS --interactive=false
stages:
  - build
  - test
build:
    stage: build
    script: 
    
    -   mvn clean package
  
    - ./jfrog rt mvn "clean package"  testrepo --build-name=my-build-name --build-number=$CI_JOB_ID
    - ./jfrog rt bce my-build-name $CI_JOB_ID
    - ./jfrog rt bp my-build-name $CI_JOB_ID
unitTests:
  stage: test
  script:
    - mvn test

   