---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-CI_ENVIRONMENT_SLUG
  namespace: KUBE_NAMESPACE
  labels:
    app: app-CI_ENVIRONMENT_SLUG
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - app-CI_ENVIRONMENT_SLUG.rishabhtest.ml
    # the secret used here is an unsigned wildcard cert for demo purposes
    # use your own or comment this out
    #secretName: tls-wildcard-demo
  rules:
  - host: app-CI_ENVIRONMENT_SLUG.rishabhtest.ml
    http:
      paths:
      - path: /login
        backend:
          serviceName: app-CI_ENVIRONMENT_SLUG
          servicePort: 8090