---
apiVersion: v1
kind: Service
metadata:
  name: blogs
  labels:
    app: blogs
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP
      name: http
  selector:
      app: blogs
 

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blogs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blogs
    spec:
      containers:
      - name: spring-blogs
        image: rishabh050189/spring-blogs:"$CI_JOB_ID"
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          timeoutSeconds: 1