---
apiVersion: v1
kind: Service
metadata:
  name: blogs
  labels:
    app: blogs
spec:
  type: NodePort
  selector:
    app: shopfront
  ports:
  - protocol: TCP
    port: 8090
    name: http
    nodePort: 30000
 

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blogs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blogs
    spec:
      containers:
      - name: spring-blogs
        image: rishabh050189/spring-blogs:214991090
        ports:
        - containerPort: 8090
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          timeoutSeconds: 1